version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gas_tracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gas_tracker_development
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gas_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: gas_tracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gas_tracker_test
    ports:
      - "5436:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
